#!/usr/bin/env python3
"""
Plot core metrics (criterion validity, discriminant validity, unjustified
abstention, selection rate) for the non-CS job evaluation summary.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Callable, Dict

import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser("Plot non-CS job metrics")
    p.add_argument("--summary_csv", type=str, required=True, help="CSV generated by aggregate_noncs_job_metrics.py")
    p.add_argument("--out_dir", type=str, default="analysis/figures_noncs")
    return p.parse_args()


def set_style() -> None:
    sns.set_theme(style="whitegrid", context="talk", font_scale=1.4)
    plt.rcParams.update({
        "figure.dpi": 120,
        "savefig.dpi": 120,
        "axes.titlesize": 24,
        "axes.titleweight": "bold",
        "axes.labelsize": 18,
        "axes.labelweight": "bold",
        "legend.fontsize": 12,
        "legend.title_fontsize": 12,
        "xtick.labelsize": 12,
        "ytick.labelsize": 12,
        "font.weight": "bold",
    })


MODEL_SHORT = {
    "anthropic/claude-sonnet-4": "claude",
    "deepseek/deepseek-chat-v3.1": "deepseek",
    "google/gemini-2.0-flash-001": "gemini-2.0",
    "google/gemini-2.5-pro": "gemini-2.5",
    "google/gemma-3-12b-it": "gemma",
    "openai/gpt-4o-mini": "gpt-4o-mini",
    "openai/gpt-5": "gpt-5",
    "meta-llama/llama-3.1-8b-instruct": "llama-8b",
    "meta-llama/llama-3.3-70b-instruct": "llama-70b",
}


def short_model_name(model: str) -> str:
    return MODEL_SHORT.get(model, model.split("/")[-1])


def compute_se(df: pd.DataFrame, value_col: str, denom_col: str) -> pd.DataFrame:
    d = df.copy()
    d["se"] = np.where(
        d[denom_col] > 0,
        np.sqrt(d[value_col] * (1.0 - d[value_col]) / d[denom_col]),
        np.nan,
    )
    return d


def plot_metric(
    df: pd.DataFrame,
    value_col: str,
    denom_col: str,
    ylabel: str,
    title: str,
    outfile: Path,
    baseline: float | None = None,
    baseline_label: str | None = None,
) -> None:
    if df.empty:
        return
    d = compute_se(df, value_col, denom_col).copy()
    d = d.sort_values(["job_type", "model_short"])
    jobs = d["job_type"].unique().tolist()
    models = sorted(d["model_short"].unique().tolist())

    fig_w = max(18, 2.5 * len(models))
    fig_h = max(10, 4 * len(jobs))
    fig, axes = plt.subplots(len(jobs), 1, figsize=(fig_w, fig_h), squeeze=False)
    for idx, job in enumerate(jobs):
        ax = axes[idx, 0]
        dj = d[d["job_type"] == job]
        sns.barplot(data=dj, x="model_short", y=value_col, ax=ax, order=models, errorbar=None, color="#4C78A8")
        for i, model in enumerate(models):
            row = dj[dj["model_short"] == model]
            if row.empty:
                continue
            se_val = row["se"].iloc[0]
            if pd.notna(se_val) and i < len(ax.patches):
                bar = ax.patches[i]
                x = bar.get_x() + bar.get_width() / 2
                y = bar.get_height()
                ax.errorbar(x, y, yerr=se_val, ecolor="#333333", capsize=3, fmt="none", lw=1)
        ax.set_ylim(0.0, 1.0)
        ax.set_xlabel("Model")
        ax.set_ylabel(ylabel)
        ax.set_title(job)
        plt.setp(ax.get_xticklabels(), rotation=0, ha="center")
        if baseline is not None and baseline_label is not None:
            ax.axhline(baseline, ls="--", lw=1.2, color="#666666")
            ax.text(
                0.99,
                baseline + 0.01,
                baseline_label,
                color="#666666",
                fontsize=10,
                ha="right",
                va="bottom",
                transform=ax.get_yaxis_transform(),
            )
    fig.suptitle(title, fontweight="bold")
    fig.tight_layout(rect=[0, 0, 1, 0.96])
    outfile.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(outfile)
    plt.close(fig)


def main() -> None:
    args = parse_args()
    summary = pd.read_csv(args.summary_csv)
    if summary.empty:
        raise RuntimeError(f"No rows in {args.summary_csv}")
    summary["model_short"] = summary["model_id"].astype(str).map(short_model_name)
    set_style()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    plot_metric(
        summary,
        value_col="criterion_validity",
        denom_col="n_strict_pairs",
        ylabel="Criterion Validity",
        title="Criterion Validity — Non-CS Jobs",
        outfile=out_dir / "criterion_validity_noncs_jobs.png",
        baseline=1 / 3,
        baseline_label="random baseline (1/3)",
    )
    plot_metric(
        summary,
        value_col="unjustified_abstention",
        denom_col="n_strict_pairs",
        ylabel="Unjustified Abstention",
        title="Unjustified Abstention — Non-CS Jobs",
        outfile=out_dir / "unjustified_abstention_noncs_jobs.png",
    )
    plot_metric(
        summary,
        value_col="discriminant_validity",
        denom_col="n_equal_pairs",
        ylabel="Discriminant Validity",
        title="Discriminant Validity — Non-CS Jobs",
        outfile=out_dir / "discriminant_validity_noncs_jobs.png",
    )
    plot_metric(
        summary,
        value_col="selection_rate_first",
        denom_col="n_equal_pairs_noab",
        ylabel="Selection Rate (First Resume)",
        title="Selection Rate on Equal Pairs — Non-CS Jobs",
        outfile=out_dir / "selection_rate_noncs_jobs.png",
        baseline=0.5,
        baseline_label="random baseline (1/2)",
    )


if __name__ == "__main__":
    main()


